version: "3"
services:
  weather:
    image: weather-report:1.0.0
    environment: 
        - MONGODB_HOST=mongodb://localhost:27017
        - DB=weather
        - DB_USER=weather_client
        - DB_PASSWORD=password1
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  mongodb:
      image: mongo:latest
      ports:
      - "27017:27017"

  mongo_seed:
      image: mongo:3.2.6
      links:
      - mongodb
      volumes:
        - ./mongo_seed:/mongo_seed
      command:
        ./mongo_seed/init.sh     