#################################################################################
# This file defines the services, service accounts, and deployments for
# the weather-report-info application.
# To apply the location and weather-report services, their service accounts, and
# their deployments:
# kubectl apply -f weather-report/platform/kube/weather.yaml
#
# Alternatively you can deploy each object separately
###################################################################################

###################################################################################
# Weather Service
###################################################################################
apiVersion: v1
kind: Service
metadata:
  name: weather
  labels:
    app: weather
    service: weather
spec:
  ports:
    - port: 8081
      name: http
  selector:
    app: weather
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: weather-report
  labels:
    account: weather
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
  labels:
    app: weather
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather
      version: v1
  template:
    metadata:
      labels:
        app: weather
        version: v1
    spec:
      serviceAccountName: weather-report
      containers:
        - name: weather
          image: localhost:32000/weatherinfo:registry
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081

